// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © bikramiter

//@version=5
strategy("Supertrend Strategy", overlay=true)

atrPeriod = input.int(10, "ATR Length", minval = 1)
factor = input.float(3.0, "Factor", minval = 0.01, step = 0.01)

[supertrend, direction] = ta.supertrend(factor, atrPeriod)

upTrend = plot(direction < 0 ? supertrend : na, "Up Trend",   color = color.green, style = plot.style_linebr, linewidth=2)
downTrend = plot(direction < 0 ? na : supertrend, "Down Trend", color = color.red,   style = plot.style_linebr, linewidth=2)

// Strategy logic
longCondition = ta.crossover(close, supertrend)
shortCondition = ta.crossunder(close, supertrend)

if (longCondition)
    strategy.entry("BUY", strategy.long)
if (shortCondition)
    strategy.entry("SELL", strategy.short)
